HTML = r"""<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><title>近期蓝光发行</title>
<style>:root{color-scheme:light dark;--bg:#f3f5f9;--card:#fff;--text:#213047;--muted:#64748b;--line:#dde4ef;--accent:#315bd6}*{box-sizing:border-box}body{background:var(--bg);color:var(--text);margin:0;font:15px/1.6 system-ui,sans-serif}main{max-width:1280px;margin:32px auto;padding:0 24px}header{display:flex;align-items:center;justify-content:space-between;gap:24px}h1{margin:0;font-size:30px}header p{color:var(--muted);margin:6px 0 22px}a{color:var(--accent);text-decoration:none}button,input,select{font:inherit;padding:8px 12px;border:1px solid var(--line);border-radius:8px;background:var(--card);color:var(--text)}button{cursor:pointer}button:disabled{opacity:.5;cursor:default}.toolbar{display:flex;flex-wrap:wrap;gap:10px;align-items:center;margin:10px 0 20px}.status{min-height:28px;color:var(--muted);white-space:pre-wrap}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(330px,1fr));gap:18px;margin:18px 0}.card{border:1px solid var(--line);border-radius:12px;background:var(--card);overflow:hidden;display:flex;min-height:250px}.poster{width:115px;flex:none;object-fit:cover;align-self:stretch;background:#dfe5f0}.placeholder{display:flex;align-items:center;justify-content:center;color:#6d7e9e;text-align:center;padding:12px;font-size:23px}.content{padding:16px;min-width:0;flex:1}.content h2{font-size:17px;line-height:1.5;margin:8px 0}.original{color:var(--muted);font-size:12px;overflow-wrap:anywhere}.badge{font-size:12px;background:#e8eefe;color:#315bd6;padding:3px 7px;border-radius:5px;margin-right:6px;display:inline-block}.overview{font-size:13px;color:var(--muted);display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient:vertical;overflow:hidden}.links{display:flex;gap:14px;margin-top:12px;font-size:13px}.paging{display:flex;gap:14px;align-items:center;justify-content:center;margin:26px}footer{color:var(--muted);font-size:12px;margin:36px 0}.error{color:#c65232}@media(prefers-color-scheme:dark){:root{--bg:#121824;--card:#1b2432;--text:#e0e7f2;--muted:#a0adc0;--line:#334053;--accent:#91b1ff}.badge{background:#293d65;color:#b4c9ff}.poster{background:#253247}}@media(max-width:600px){main{padding:0 14px;margin-top:20px}.grid{grid-template-columns:1fr}header{display:block}h1{font-size:25px}}</style></head><body><main>
<header><div><h1>近期蓝光发行</h1><p>美国发行日历 · Blu-ray / 4K UHD · 按影片年份匹配 TMDB 元数据</p></div><a href="/" target="_blank" rel="noopener noreferrer">返回 MoviePilot ↗</a></header>
<div class="toolbar"><button id="prev-month">‹ 上月</button><input id="month" type="month" aria-label="发行月份"><button id="next-month">下月 ›</button><select id="format" aria-label="光盘格式"><option value="all">全部格式</option><option value="4k">4K UHD</option><option value="bluray">Blu-ray</option></select><select id="period" aria-label="发行状态"><option value="all">整月发行</option><option value="released">已发行</option><option value="upcoming">即将发行</option></select><button id="refresh">更新日历</button><button id="retry">匹配当前页元数据</button></div>
<div id="status" class="status" role="status">正在加载发行日历…</div><section id="grid" class="grid"></section><div class="paging"><button id="prev-page">上一页</button><span id="page-info"></span><button id="next-page">下一页</button></div>
<footer>发行日期来自 <a href="https://www.blu-ray.com/movies/releasedates.php" target="_blank" rel="noopener noreferrer">Blu-ray.com</a>；包含新版本、修复版和再版，不代表影片首映或站点资源上线日期。无法可靠匹配的套装、剧集和同名影片保留原始名称。<br>本页面使用 TMDB API，但未经 TMDB 认可或认证。仅浏览发行信息，不自动添加订阅、下载或保存影视库。</footer></main>
<script>(()=>{'use strict';const base='/api/v1/plugin/BlurayReleaseCalendar',$=id=>document.getElementById(id);let page=1,total=0,items=[],generation=0,matching=false;const now=new Date();$('month').value=now.getFullYear()+'-'+String(now.getMonth()+1).padStart(2,'0');
function token(){try{return JSON.parse(localStorage.getItem('auth')||'{}').token||''}catch{return ''}}
async function api(path,options={}){const response=await fetch(base+path,{...options,headers:{'Authorization':'Bearer '+token(),...options.headers}});if(response.status===401||response.status===403)throw Error('请先在同一地址的 MoviePilot 登录，然后刷新此页。');if(!response.ok)throw Error('请求未完成，请稍后重试（'+response.status+'）');return response.json()}
function status(text){$('status').textContent=text}
function node(tag,text,cls){const e=document.createElement(tag);if(text)e.textContent=text;if(cls)e.className=cls;return e}
function link(text,url){const a=node('a',text);a.href=url;a.target='_blank';a.rel='noopener noreferrer';return a}
function render(){const grid=$('grid');grid.replaceChildren();for(const item of items){const meta=item.metadata||{},card=node('article',null,'card');if(meta.poster&&/^https:\/\/image\.tmdb\.org\/t\/p\/w342\/[\w.-]+$/.test(meta.poster)){const img=node('img',null,'poster');img.src=meta.poster;img.alt=meta.title||item.title;img.loading='lazy';img.referrerPolicy='no-referrer';card.append(img)}else card.append(node('div',item.format==='4K UHD'?'4K\nUHD':'Blu-ray','poster placeholder'));const body=node('div',null,'content');body.append(node('span',item.release_date,'badge'),node('span',item.format,'badge'),node('h2',meta.title||item.title),node('div',item.title+(item.year?' ('+item.year+')':''),'original'),node('p',[item.studio,item.casing,item.edition].filter(Boolean).join(' · '),'original'));if(meta.state==='matched'){body.append(node('p',meta.overview||'暂无简介','overview'));if(meta.rating)body.append(node('small','TMDB '+Number(meta.rating).toFixed(1))}else body.append(node('p',meta.state==='pending'?'正在匹配元数据…':meta.message||'保留原始发行名称','original'));const links=node('div',null,'links');links.append(link('发行详情 ↗',item.source_url));if(meta.tmdb_url&&/^https:\/\/www\.themoviedb\.org\/movie\/\d+$/.test(meta.tmdb_url))links.append(link('影片资料 ↗',meta.tmdb_url));body.append(links);card.append(body);grid.append(card)}$('page-info').textContent='第 '+page+' / '+Math.max(1,Math.ceil(total/24))+' 页 · '+total+' 个发行版本';$('prev-page').disabled=page<=1;$('next-page').disabled=page*24>=total}
async function load(refresh=false){const gen=++generation;status('正在加载发行日历…');$('refresh').disabled=true;try{const data=await api('/releases?'+new URLSearchParams({month:$('month').value,format:$('format').value,period:$('period').value,page,refresh:refresh?'1':'0'}));if(gen!==generation)return;items=data.items;total=data.total;render();status((data.warning?data.warning+'\n':'')+'美国 · '+data.month+(data.updated?' · 更新于 '+new Date(data.updated*1000).toLocaleString():''));void matchPage(gen)}catch(error){if(gen===generation)status(error.message)}finally{if(gen===generation)$('refresh').disabled=false}}
async function matchPage(gen=generation){if(matching)return;matching=true;$('retry').disabled=true;try{const pending=items.filter(x=>['pending','error'].includes(x.metadata?.state||'pending')).map(x=>x.id);for(let start=0;start<pending.length;start+=6){if(gen!==generation)break;const data=await api('/match',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({month:$('month').value,ids:pending.slice(start,start+6)})});if(gen!==generation)break;for(const item of items)if(data[item.id])item.metadata=data[item.id];render()}}catch(error){if(gen===generation)status(error.message)}finally{matching=false;$('retry').disabled=false;if(gen!==generation)void matchPage(generation)}}
for(const id of ['month','format','period'])$(id).onchange=()=>{page=1;load()};function shift(n){const [y,m]=$('month').value.split('-').map(Number),d=new Date(y,m-1+n,1);$('month').value=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0');page=1;load()}$('prev-month').onclick=()=>shift(-1);$('next-month').onclick=()=>shift(1);$('prev-page').onclick=()=>{page--;load()};$('next-page').onclick=()=>{page++;load()};$('refresh').onclick=()=>load(true);$('retry').onclick=()=>matchPage();load();})();</script></body></html>"""
